crypto_libraries:
  - name: openssl
    version: 3.0.13
    url: https://www.openssl.org/source/openssl-3.0.13.tar.gz
  - name: mbedtls
    version: 3.6.0
    url: https://github.com/Mbed-TLS/mbedtls/archive/refs/tags/v3.6.0.tar.gz

model_path: data/06_models/crypto_classifier.pth

